
executors:
  default:
    docker:
      - image: cimg/python:3.10
    working_directory: ~/repo

version: 2.1
jobs:
  setup:
    executor: default
    steps:
      - checkout
      - run: 
          name: installing required modules 
          command: |
            python -m venv venv
            source /venv/bin/activate
            pip install -r requirements.txt


  tests:
    executor: default
    steps:
      - checkout
      - run:
          name: test phase 
          command: pytset

workflows:
  version: 2
  build_and_test:
    jobs:
      - setup
      - tests:
          requires:
            - setup

