
executors:
  default:
    docker:
      - image: cimg/python:3.10
    working_directory: ~/repo

version: 2.1
jobs:
  setup:
    executor: default
    steps:
      - checkout
      - run: 
          name: installing required modules 
          command: |
            python3 -m venv venv
            source ./venv/bin/activate
            pip install -r requirements.txt
      - persist_to_workspace:
          root: ~/repo
          paths:
            - venv


  tests:
    executor: default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: test phase 
          command: |
            source ./venv/bin/activate
            pytest

  env_var_check:
    executor: default
    steps:
    

workflows:
  version: 2
  build_and_test:
    jobs:
      - setup
      - tests:
          requires:
            - setup

